### PR TITLE
(FEAT)camera runtime permission, butter kniving for data binding 

### PR DESCRIPTION
**Pull request by PiSolve**
Have changed 
- Data binding 
- Camera runt time permission 
- min sdk version and target sdk version 
- utils class for checking if Has permission or not .

### CODE REVIEW

**Comment by arynchoong** [comment]
Hi Renu,
Your pull request has conflicts with the updated merged repository. 
Could you please update, and create another pull request?
Thanks,
Yue Lin.(arynchoong)

**Comment by PiSolve** [comment]
@arynchoong
Resolved conflicts . I can see some crash once picture is captured. Need to change the code (onActivity result once image is captured)
will do that in another PR.
And I hope all todo tasks are listed in trello

**Comment by PiSolve** [comment]
@Team:
request you to create a development branch rather than merging everything in `master` directly
all pull requests can be merged to `development` then and intermittently  `development` can be merged to `master`
will be helpful in longer term , as more n more people will start contributing . 
Thanks

**Comment by cheeyim** [comment]
develop branch created

**Pull request merged**
